baseURL = 'https://pete399c1.github.io/portfolio/'
languageCode = 'en-us'
theme = 'blowfish'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
identifier = "github"
pre = "github"
url = "https://github.com/pete399c1"
weight = 10

[[menu.main]]
identifier = "youtube"
pre = "youtube"
url = "https://www.youtube.com"
weight = 10